services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=ecommerce_development
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"

  web:
    build:
      context: ./ECOMMERCE-BACKEND-RUBY-RAILS-ANGULAR-TAILWIND-SASS/backend
    env_file:
      - .env
    environment:
      # Passamos as variáveis separadas para evitar erro de parsing na URL com '@'
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=db
      - MP_ACCESS_TOKEN=${MP_ACCESS_TOKEN}
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./ECOMMERCE-BACKEND-RUBY-RAILS-ANGULAR-TAILWIND-SASS/backend:/app
      - /app/tmp 
    # O comando limpa o PID do servidor para evitar erro de "server already running"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"

  frontend:
    build:
      context: ./ECOMMERCE-FRONTEND-ANGULAR-TAILWIND-SASS-NODEJS
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./ECOMMERCE-FRONTEND-ANGULAR-TAILWIND-SASS-NODEJS:/app
      - /app/node_modules 
    depends_on:
      - web

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: santhiago34343434@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: